import type { Source,Report,DimensionKey,ProviderId } from '../types/domain.ts';
import { openAIAdapter } from './providers/openai.ts';import {kimiAdapter} from './providers/kimi.ts';import {claudeAdapter} from './providers/claude.ts';
import {maxPromptCharacters} from '../config/providers.ts';
const adapters={openai:openAIAdapter,kimi:kimiAdapter,claude:claudeAdapter};
const system=`你是一位谨慎的文本观察者，不是心理诊断者。仅根据给定材料做可撤回的语言风格假设。中文回答，避免定论和数字分数。引用必须是材料中的连续原文片段，逐字一致，区分观察与推测并提供替代解释。MBTI、九型人格和大五人格是启发式框架，不是诊断工具。材料不足时明确说证据不足。仅输出JSON：{"summary":"...","caveat":"...","dimensions":{"mbti":[{"observation":"...","inference":"...","alternative":"...","evidence":[{"quote":"...","sourceId":"...","page":1}]}],"enneagram":[...],"bigFive":[...]}}。每个维度给1-3条，sourceId必须用输入ID，PDF的page必须为页码。`;
export function buildPrompt(sources:Source[]){return `${system}\n\n材料：\n${sources.map(s=>`[sourceId=${s.id}; title=${s.title}]\n${s.kind==='pdf'?(s.pages||[]).map(p=>`[page=${p.page}] ${p.text}`).join('\n'):s.text}`).join('\n\n')}`}
export function validateReport(raw:unknown,profileId:string,sources:Source[]):Report{const o=typeof raw==='string'?JSON.parse(raw):raw as any;if(!o||typeof o.summary!=='string'||typeof o.caveat!=='string'||!o.dimensions)throw new Error('报告格式不完整，请重试。');const dimensions={} as Report['dimensions'];for(const k of ['mbti','enneagram','bigFive'] as DimensionKey[]){if(!Array.isArray(o.dimensions[k]))throw new Error('报告缺少人格维度，请重试。');dimensions[k]=o.dimensions[k].flatMap((f:any)=>{if(typeof f.observation!=='string'||typeof f.inference!=='string'||typeof f.alternative!=='string'||!Array.isArray(f.evidence))return[];const evidence=f.evidence.flatMap((e:any)=>{const s=sources.find(x=>x.id===e.sourceId);if(!s||typeof e.quote!=='string'||!e.quote.trim())return[];if(s.kind==='pdf'){const page=s.pages?.find(p=>p.page===e.page);return page?.text.includes(e.quote)?[{quote:e.quote,sourceId:s.id,page:page.page}]:[]}return s.text.includes(e.quote)?[{quote:e.quote,sourceId:s.id}]:[]});return evidence.length?[{observation:f.observation,inference:f.inference,alternative:f.alternative,evidence}]:[]})}return{id:crypto.randomUUID(),profileId,createdAt:Date.now(),sourceIds:sources.map(s=>s.id),dimensions,summary:o.summary,caveat:o.caveat,stale:false}}
export function preflightReport(sources:Source[]){const characters=buildPrompt(sources).length;return{characters,limit:maxPromptCharacters,ok:characters<=maxPromptCharacters}}
export async function requestReport(provider:ProviderId,model:string,apiKey:string,sources:Source[],signal?:AbortSignal):Promise<Report>{if(!apiKey.trim())throw new Error('请先填写 API Key。');if(!sources.length)throw new Error('至少选择一份材料。');const prompt=buildPrompt(sources);if(prompt.length>maxPromptCharacters)throw new Error(`材料合计约 ${prompt.length.toLocaleString()} 字符，超过单次安全上限 ${maxPromptCharacters.toLocaleString()}。请取消部分材料或缩短内容后再试；系统不会自动截断。`);const text=await adapters[provider].request({model,apiKey,prompt,signal});try{return validateReport(text,'',sources)}catch(e:any){if(e instanceof SyntaxError)throw new Error('服务商返回内容不是有效 JSON，无法安全展示。请重试或更换模型。');throw e}}

