import { useEffect,useState } from 'react';
import type { Profile,Source,Report,ProviderId,ArchiveData } from '../types/domain';
import { providers } from '../config/providers';
import { archiveRuntime as runtime } from '../runtime/archiveRuntime';
const date=(n:number)=>new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(n);
export function App(){
 const [db,setDb]=useState<ArchiveData>({profiles:[],sources:[],reports:[]}),[ready,setReady]=useState(false),[active,setActive]=useState(''),[provider,setProvider]=useState<ProviderId>('openai'),[model,setModel]=useState(providers[0].defaultModel),[apiKey,setApiKey]=useState(''),[showKey,setShowKey]=useState(false),[settings,setSettings]=useState(false),[toast,setToast]=useState(''),[modal,setModal]=useState(''),[name,setName]=useState(''),[editingProfile,setEditingProfile]=useState<Profile|null>(null),[deleteProfile,setDeleteProfile]=useState<Profile|null>(null),[material,setMaterial]=useState<Source|null>(null),[matTitle,setMatTitle]=useState(''),[matText,setMatText]=useState(''),[chosen,setChosen]=useState<string[]>([]),[generating,setGenerating]=useState(false),[selectedReport,setSelectedReport]=useState(''),[busy,setBusy]=useState(false),[incoming,setIncoming]=useState<ArchiveData|null>(null),[dupes,setDupes]=useState<ReturnType<typeof runtime.conflicts>>([]),[choices,setChoices]=useState<Record<string,'keep'|'replace'>>({});
 async function refresh(){setDb(await runtime.load());setReady(true)}useEffect(()=>{void refresh()},[]);useEffect(()=>{setApiKey('');setModel(providers.find(p=>p.id===provider)!.defaultModel)},[provider]);
 const profile=db.profiles.find(x=>x.id===active),sources=db.sources.filter(x=>x.profileId===active),reports=db.reports.filter(x=>x.profileId===active),shownReport=reports.find(x=>x.id===selectedReport)||reports[0];
 useEffect(()=>{setChosen(sources.map(x=>x.id))},[active,sources.length]);
 function say(s:string){setToast(s);setTimeout(()=>setToast(''),3800)}
 async function saveProfile(){if(!name.trim())return;const p=await runtime.saveProfile(name.trim(),editingProfile||undefined);await refresh();setActive(p.id);setEditingProfile(null);setName('');setModal('')}
 async function removeProfile(){if(!deleteProfile)return;await runtime.deleteProfile(deleteProfile.id);if(active===deleteProfile.id)setActive('');await refresh();setDeleteProfile(null);say('档案及其材料、报告已删除。')}
 async function saveMaterial(){if(!profile||!matText.trim())return;await runtime.saveText(profile.id,matTitle.trim()||material?.title||('文字材料 '+(sources.length+1)),matText.trim(),material||undefined);await refresh();setModal('');setMaterial(null)}
 async function addPdf(file?:File){if(!file||!profile)return;setBusy(true);try{const s=await runtime.addPdf(file,profile.id);await refresh();say(`已提取 ${s.pages?.length||0} 页文字。`)}catch(e:any){say(e.message||'PDF 解析失败。')}finally{setBusy(false)}}
 async function removeSource(s:Source){if(!confirm(`删除「${s.title}」？`))return;await runtime.deleteSource(s);await refresh();setSelectedReport('')}
 async function generate(){const used=sources.filter(s=>chosen.includes(s.id));if(!used.length){say('至少选择一份材料。');return}const check=runtime.preflight(used);if(!check.ok){say('材料约 '+check.characters.toLocaleString()+' 字符，超过单次安全上限。请取消部分材料或缩短内容；系统不会截断。');return}if(!apiKey.trim()){setSettings(true);say('请先添加 API Key。');return}if(!confirm(`将发送 ${used.length} 份材料至 ${provider}。材料会离开本机，服务商可能据此收费。继续吗？`))return;setGenerating(true);try{const saved=await runtime.generate(provider,model,apiKey,active,used);await refresh();setSelectedReport(saved.id);say('报告已生成，原文引用已校验。')}catch(e:any){say(e.message||'生成失败。')}finally{setGenerating(false)}}
 function saveBackup(){const url=URL.createObjectURL(runtime.backup(db)),a=document.createElement('a');a.href=url;a.download='星象档案-本地备份.json';a.click();URL.revokeObjectURL(url)}
 async function importFile(file?:File){if(!file)return;try{const data=await runtime.readBackup(file),c=runtime.conflicts(db,data);if(c.length){setIncoming(data);setDupes(c);setChoices(Object.fromEntries(c.map(x=>[x.id,'keep'])))}else{await runtime.merge(data,{});await refresh();say('备份已合并。')}}catch(e:any){say(e.message||'无法读取备份。')}}
 async function merge(){if(!incoming)return;await runtime.merge(incoming,choices);await refresh();setIncoming(null);say('备份已合并。')}
 return <div className="shell"><aside className="rail"><div className="brand"><b>✦</b><span>星象档案<small>PERSONALITY ARCHIVE</small></span></div><div className="rail-title">你的档案<button onClick={()=>{setEditingProfile(null);setName('');setModal('profile')}}>＋</button></div><div className="people">{db.profiles.map((p,i)=><button className={active===p.id?'person active':'person'} key={p.id} onClick={()=>{setActive(p.id);setSelectedReport('')}}><i className={'avatar a'+i%4}>{p.name[0]}</i><span>{p.name}<small>{db.sources.filter(s=>s.profileId===p.id).length} 份材料</small></span></button>)}{!db.profiles.length&&<p className="rail-empty">还没有档案，<br/>从添加一个人开始。</p>}</div><div className="rail-bottom"><button onClick={saveBackup}>↓　导出本地备份</button><label>↑　合并导入备份<input type="file" accept="application/json,.json" onChange={e=>void importFile(e.target.files?.[0])}/></label><small>● 只保存在此设备</small></div></aside>
 <main><header><div className="breadcrumbs"><button className="home-link" onClick={()=>{setActive('');setSelectedReport('')}}>⌂　星象档案</button>　/　<b>{profile?.name||'全部档案'}</b></div><div className="header-actions"><button className="header-tool" onClick={saveBackup}>↓　导出备份</button><label className="header-tool import-tool">↑　导入备份<input type="file" accept="application/json,.json" onChange={e=>void importFile(e.target.files?.[0])}/></label><button className="settings" onClick={()=>setSettings(true)}>⚙　API 设置</button></div></header>{!ready?<div className="center">正在打开本地档案…</div>:!profile?(db.profiles.length===0?<section className="welcome"><div className="constellation">✦</div><p className="eyebrow">A GENTLE STUDY OF PEOPLE</p><h1>留下一些言语，<br/><em>慢慢认识一个人。</em></h1><p>把对话、文字与想法收进档案。让每一种判断，都能回到原文里寻找依据。</p><button className="primary" onClick={()=>{setEditingProfile(null);setName('');setModal('profile')}}>＋　建立第一个人格盒子</button><small>✧ 你的材料仅保存在此浏览器中</small></section>:<section className="profile-home"><div className="home-heading"><div><p className="eyebrow">YOUR PEOPLE, YOUR NOTES</p><h1>人格盒子</h1><p>每个人都有一页自己的档案，从一段文字开始。</p></div><button className="primary" onClick={()=>{setEditingProfile(null);setName('');setModal('profile')}}>＋　新增人格盒子</button></div><div className="profile-grid">{db.profiles.map((p,i)=><button className="profile-tile" key={p.id} onClick={()=>setActive(p.id)}><span className={'tile-avatar a'+i%4}>{p.name[0]}</span><strong>{p.name}</strong><small>{db.sources.filter(s=>s.profileId===p.id).length} 份材料　·　{db.reports.filter(r=>r.profileId===p.id).length} 份报告</small><i>打开档案　→</i></button>)}</div></section>):<div className="content"><section className="person-head"><div><p className="eyebrow">PERSONAL FILE　✦　{new Date(profile.createdAt).getFullYear()} — 至今</p><h1>{profile.name}<i>.</i></h1><p>这里收集关于 {profile.name} 的文字与观察。结论只是一种假设，证据始终来自原文。</p></div><div className="buttons"><button className="outline" onClick={()=>{setEditingProfile(profile);setName(profile.name);setModal('profile')}}>✎ 编辑档案</button><button className="outline danger" onClick={()=>setDeleteProfile(profile)}>⌫</button></div></section>
 <div className="stats"><span>▤　<b>{sources.length}</b> 份材料</span><i/><span>✧　<b>{reports.length}</b> 份观察报告</span><i/><span>◷　<b>{reports[0]?date(reports[0].createdAt):'尚未生成'}</b>　最近记录</span></div>
 <section className="materials"><div className="sect-head"><div><label>COLLECTED WORDS</label><h2>材料与片段</h2></div><div className="buttons"><label className="outline upload">↑　{busy?'解析中…':'上传 PDF'}<input type="file" accept="application/pdf" disabled={busy} onChange={e=>void addPdf(e.target.files?.[0])}/></label><button className="primary small" onClick={()=>{setMaterial(null);setMatTitle('');setMatText('');setModal('material')}}>＋ 添加文字</button></div></div>{!sources.length?<div className="empty">“　<b>档案还很安静</b><p>添加一些文字或对话片段，作为未来观察的依据。</p></div>:<div className="source-list">{sources.map(s=><article key={s.id}><div className="type">{s.kind==='pdf'?'PDF · 只读':'文字'}　·　{s.kind==='pdf'?`${s.pages?.length} 页文字`:'文本片段'}</div><div className="source-body"><div className="source-title"><h3>{s.title}</h3><span>{s.kind==='text'&&<button aria-label="编辑文字材料" onClick={()=>{setMaterial(s);setMatTitle(s.title);setMatText(s.text);setModal('material')}}>✎</button>}<button aria-label="删除材料" onClick={()=>void removeSource(s)}>⌫</button></span></div><p>“{s.text.slice(0,240)}{s.text.length>240?'…':''}”</p>{s.pages?.length>0&&<div className="pages">{s.pages.slice(0,6).map(x=><small key={x.page}>第 {x.page} 页</small>)}</div>}<small>添加于 {date(s.createdAt)}</small></div></article>)}</div>}</section>
 <section className="report"><div className="report-intro"><div><label>REFLECTION, NOT A DIAGNOSIS</label><h2>人格观察</h2><p>从材料中寻找模式，并保留不同解释的空间。</p></div><span>✧</span></div><div className="generator"><div className="generator-head"><b>选择用于本次观察的材料</b><button onClick={()=>setChosen(chosen.length===sources.length?[]:sources.map(x=>x.id))}>{chosen.length===sources.length?'取消全选':'全选'}</button></div><p>默认选中全部材料。内容会发送至所选 AI 服务商。</p>{sources.length>0&&!runtime.preflight(sources.filter(s=>chosen.includes(s.id))).ok&&<div className="preflight-warning">所选材料过长（约 {runtime.preflight(sources.filter(s=>chosen.includes(s.id))).characters.toLocaleString()} 字符）。请取消部分材料或缩短内容后再发送；不会自动截断。</div>}{!sources.length?<div className="no-data">添加材料后即可生成观察报告。</div>:sources.map(s=><label className="pick" key={s.id}><input type="checkbox" checked={chosen.includes(s.id)} onChange={e=>setChosen(e.target.checked?[...chosen,s.id]:chosen.filter(x=>x!==s.id))}/><span><b>{s.title}</b><small>{s.kind==='pdf'?'PDF · ':''}{s.text.length} 字符</small></span><small>{s.kind==='pdf'?'PDF':'文字'}</small></label>)}<div className="generate-row"><small>● 使用 {providers.find(p=>p.id===provider)?.label} · {model}</small><button className="primary" disabled={!sources.length||generating} onClick={()=>void generate()}>{generating?'◌ 正在整理证据…':'✧ 生成观察报告'}</button></div><div className="transmit">ⓘ 点击生成后才会发送所选材料；AI 服务可能产生费用。　<button onClick={()=>setSettings(true)}>API 设置与隐私说明</button></div></div></section>
 <section className="history"><div className="sect-head"><div><label>SAVED REFLECTIONS</label><h2>报告历史</h2></div><span>{reports.length} 份</span></div>{!reports.length?<div className="empty-history">尚无观察报告。每次生成后，都会保留一个可回看的版本。</div>:<>{reports.map((r,i)=><button className={'history-row '+(shownReport?.id===r.id?'active':'')} key={r.id} onClick={()=>setSelectedReport(r.id)}><span>{i?'◇':'✦'}</span><b>{date(r.createdAt)} 的观察<small>{r.sourceIds.length} 份材料 · MBTI、九型人格、大五人格</small></b>{r.stale&&<em>材料有更新</em>}<i>→</i></button>)}{shownReport&&<div className="report-card"><small className="date-label">观察报告 · {date(shownReport.createdAt)}{shownReport.stale?'　·　材料有更新':''}</small><p className="summary">{shownReport.summary}</p><div className="caveat">✧ {shownReport.caveat}</div>{(['mbti','enneagram','bigFive'] as const).map((k,i)=><section className="dimension" key={k}><h3><i>0{i+1}</i>{['MBTI','九型人格','大五人格'][i]}<small>工作假设</small></h3>{shownReport.dimensions[k].length?shownReport.dimensions[k].map((f,j)=><div className="finding" key={j}><div><label>观察到</label><p>{f.observation}</p></div><div><label>我倾向于认为</label><p>{f.inference}</p></div><p className="alt"><label>其他可能</label>{f.alternative}</p>{f.evidence.map((e,n)=><blockquote key={n}>“{e.quote}”<small>— {db.sources.find(x=>x.id===e.sourceId)?.title||'来源材料'}{e.page?` · 第 ${e.page} 页`:''}</small></blockquote>)}</div>):<p className="no-data">目前没有可核验的引文，暂不展示判断。</p>}</section>)}<small className="disclaimer">这是一种基于文字材料的探索性阅读，不是心理测量或诊断。语言会受情境、编辑与表达习惯影响。</small></div>}</>}</section></div>}</main>
 {toast&&<div className="toast">{toast}</div>}
 {settings&&<div className="shade"><section className="modal"><div className="modal-head"><div><label>YOUR OWN API KEY</label><h2>连接 AI 服务</h2></div><button onClick={()=>setSettings(false)}>×</button></div><p>API Key 仅保存在当前页面内存中，刷新页面后会清除。不会写入浏览器存储或备份。</p><label className="field">服务商<select value={provider} onChange={e=>setProvider(e.target.value as ProviderId)}>{providers.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></label><label className="field">模型<select value={model} onChange={e=>setModel(e.target.value)}>{providers.find(p=>p.id===provider)!.models.map(x=><option key={x}>{x}</option>)}</select></label><label className="field">API Key<div className="key"><input value={apiKey} onChange={e=>setApiKey(e.target.value)} type={showKey?'text':'password'} autoComplete="off" spellCheck={false} placeholder="粘贴你的 API Key"/><button onClick={()=>setShowKey(!showKey)}>{showKey?'隐藏':'显示'}</button></div></label><div className="model-note">模型名称是默认选项，不代表你的账户一定有权限；可按服务商控制台调整。</div><div className="warning"><b>关于浏览器直连</b><p>请求从浏览器直接发送给服务商。运行中的网页脚本可能读取当前 Key；服务商也可能因 CORS、Key 权限或账户设置拒绝请求。请只在可信部署环境使用，并留意服务商费用。</p></div><div className="modal-actions"><button className="link" onClick={()=>{setApiKey('');say('已清除当前页面中的 API Key。')}}>清除 Key</button><button className="primary" onClick={()=>setSettings(false)}>完成</button></div></section></div>}
 {modal==='profile'&&<div className="shade"><section className="modal compact"><div className="modal-head"><div><label>A PERSON IN FOCUS</label><h2>{editingProfile?'编辑档案':'新建人格盒子'}</h2></div><button onClick={()=>setModal('')}>×</button></div><label className="field">姓名或称呼<input autoFocus value={name} maxLength={50} onChange={e=>setName(e.target.value)} onKeyDown={e=>e.key==='Enter'&&void saveProfile()} placeholder="例如：林间来信"/></label><div className="modal-actions"><button className="outline" onClick={()=>setModal('')}>取消</button><button className="primary" disabled={!name.trim()} onClick={()=>void saveProfile()}>{editingProfile?'保存修改':'创建档案'}</button></div></section></div>}
 {modal==='material'&&<div className="shade"><section className="modal wide"><div className="modal-head"><div><label>A NOTE TO REMEMBER</label><h2>{material?'编辑材料':'添加文字材料'}</h2></div><button onClick={()=>setModal('')}>×</button></div><label className="field">标题<input value={matTitle} onChange={e=>setMatTitle(e.target.value)} placeholder="例如：关于周末计划的对话"/></label><label className="field">原文<textarea autoFocus rows={9} value={matText} onChange={e=>setMatText(e.target.value)} placeholder="粘贴一段文字、对话或观察……"/></label><small>建议保留原始语气与句式，方便报告回到具体语句寻找依据。</small><div className="modal-actions"><button className="outline" onClick={()=>setModal('')}>取消</button><button className="primary" disabled={!matText.trim()} onClick={()=>void saveMaterial()}>{material?'保存修改':'收进档案'}</button></div></section></div>}
 {deleteProfile&&<div className="shade"><section className="modal compact"><div className="modal-head"><div><label>REMOVE PERSON</label><h2>删除「{deleteProfile.name}」？</h2></div><button onClick={()=>setDeleteProfile(null)}>×</button></div><p>这会一并删除此档案下 {db.sources.filter(s=>s.profileId===deleteProfile.id).length} 份材料和 {db.reports.filter(r=>r.profileId===deleteProfile.id).length} 份报告，无法撤销。</p><div className="modal-actions"><button className="outline" onClick={()=>setDeleteProfile(null)}>保留档案</button><button className="remove" onClick={()=>void removeProfile()}>确认删除</button></div></section></div>}
 {incoming&&<div className="shade"><section className="modal wide"><div className="modal-head"><div><label>MERGE LOCAL BACKUP</label><h2>处理重复项目</h2></div><button onClick={()=>setIncoming(null)}>×</button></div><p>备份中有 {dupes.length} 个 ID 与当前档案重复。选择保留现有项目，或用备份覆盖。</p><div className="duplicates">{dupes.map(c=><label key={c.id}><span><b>{c.kind}</b><small>{c.label}</small></span><select value={choices[c.id]} onChange={e=>setChoices({...choices,[c.id]:e.target.value as 'keep'|'replace'})}><option value="keep">保留当前</option><option value="replace">用备份覆盖</option></select></label>)}</div><div className="modal-actions"><button className="outline" onClick={()=>setIncoming(null)}>取消</button><button className="primary" onClick={()=>void merge()}>合并备份</button></div></section></div>}
 </div>
}

